name: MNN Code Review

permissions:
  contents: read
  pull-requests: write
  models: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANGUAGE: Chinese
          USE_GITHUB_MODELS: true
          LOG_LEVEL: debug
          max_tokens: 10240
          MAX_PATCH_LENGTH: 204800
          IGNORE_PATTERNS: "**/*.md,**/*.yml"
